#!/usr/bin/env sh
# Symphony install script
# Usage: curl -fsSL https://raw.githubusercontent.com/odysseus0/symphony/main/install.sh | sh
#
# Installs the latest Symphony release binary to ~/.local/bin (or /usr/local/bin if writable).
# The release includes a bundled ERTS — no Erlang/Elixir installation required.

set -e

REPO="odysseus0/symphony"
INSTALL_DIR=""
BIN_NAME="symphony"

# ── Detect platform ──────────────────────────────────────────────────────────

detect_target() {
  OS="$(uname -s)"
  ARCH="$(uname -m)"

  case "$OS" in
    Darwin)
      case "$ARCH" in
        arm64)  echo "macos-arm64" ;;
        x86_64) echo "macos-x86_64" ;;
        *)      die "Unsupported macOS architecture: $ARCH" ;;
      esac
      ;;
    Linux)
      case "$ARCH" in
        x86_64)  echo "linux-x86_64" ;;
        aarch64) echo "linux-arm64" ;;
        arm64)   echo "linux-arm64" ;;
        *)       die "Unsupported Linux architecture: $ARCH" ;;
      esac
      ;;
    *)
      die "Unsupported operating system: $OS"
      ;;
  esac
}

# ── Helpers ───────────────────────────────────────────────────────────────────

die() {
  echo "ERROR: $*" >&2
  exit 1
}

info() {
  echo "==> $*"
}

need_cmd() {
  command -v "$1" > /dev/null 2>&1 || die "Required command not found: $1"
}

# ── Choose install directory ──────────────────────────────────────────────────

choose_install_dir() {
  if [ -w "/usr/local/bin" ]; then
    echo "/usr/local/bin"
  else
    local_bin="${HOME}/.local/bin"
    mkdir -p "$local_bin"
    echo "$local_bin"
  fi
}

# ── Main ─────────────────────────────────────────────────────────────────────

main() {
  need_cmd curl
  need_cmd tar

  TARGET="$(detect_target)"
  info "Detected platform: $TARGET"

  # Fetch latest release version from GitHub API
  info "Fetching latest release info..."
  LATEST_TAG="$(curl -fsSL "https://api.github.com/repos/${REPO}/releases/latest" \
    | grep '"tag_name"' \
    | head -1 \
    | sed 's/.*"tag_name": *"\([^"]*\)".*/\1/')"

  if [ -z "$LATEST_TAG" ]; then
    die "Could not determine latest release. Check https://github.com/${REPO}/releases"
  fi

  VERSION="${LATEST_TAG#v}"
  info "Latest version: $VERSION"

  TARBALL="symphony-${VERSION}-${TARGET}.tar.gz"
  DOWNLOAD_URL="https://github.com/${REPO}/releases/download/${LATEST_TAG}/${TARBALL}"

  INSTALL_DIR="$(choose_install_dir)"
  info "Installing to: $INSTALL_DIR"

  # Download tarball into a temp directory
  TMP_DIR="$(mktemp -d)"
  trap 'rm -rf "$TMP_DIR"' EXIT

  info "Downloading $TARBALL..."
  curl -fsSL --progress-bar "$DOWNLOAD_URL" -o "${TMP_DIR}/${TARBALL}"

  # Extract release
  info "Extracting..."
  tar -xzf "${TMP_DIR}/${TARBALL}" -C "$TMP_DIR"

  # The release tarball from mix release contains bin/symphony (the start script)
  # and the full ERTS tree.  We install the entire release under ~/.local/share/symphony
  # (or /usr/local/share/symphony) and create a symlink in the bin directory.

  if [ -w "/usr/local/share" ]; then
    SHARE_DIR="/usr/local/share/symphony"
  else
    SHARE_DIR="${HOME}/.local/share/symphony"
  fi

  rm -rf "$SHARE_DIR"
  mkdir -p "$(dirname "$SHARE_DIR")"
  mv "${TMP_DIR}/symphony" "$SHARE_DIR"

  # Create a real CLI wrapper script in the bin dir.
  # The OTP release places a low-level launcher at $SHARE_DIR/bin/symphony that
  # only understands OTP commands (start/stop/foreground/…).  We need the full
  # on/off/status/logs/intervene CLI that the project ships in bin/symphony.
  # We generate a thin wrapper that delegates to the OTP foreground runner for
  # "on" and uses the release's stop command for "off".
  BIN_PATH="${INSTALL_DIR}/${BIN_NAME}"
  rm -f "$BIN_PATH"

  cat > "$BIN_PATH" << WRAPPER
#!/usr/bin/env sh
# Symphony CLI wrapper — generated by install.sh $VERSION
RELEASE_DIR="${SHARE_DIR}"
OTP_BIN="\${RELEASE_DIR}/bin/symphony"

die() { echo "ERROR: \$*" >&2; exit 1; }

case "\${1:-}" in
  on)
    shift
    # Parse optional --port and --logs-root; remaining arg is optional WORKFLOW.md path
    PORT=""
    LOGS_ROOT=""
    WORKFLOW=""
    while [ \$# -gt 0 ]; do
      case "\$1" in
        --port)       PORT="\$2";      shift 2 ;;
        --logs-root)  LOGS_ROOT="\$2"; shift 2 ;;
        --i-understand-*) shift ;;  # forward compat; accepted silently
        --*)          die "Unknown option: \$1" ;;
        *)            WORKFLOW="\$1"; shift ;;
      esac
    done
    WORKFLOW="\${WORKFLOW:-\$(pwd)/WORKFLOW.md}"
    [ -f "\$WORKFLOW" ] || die "Workflow file not found: \$WORKFLOW"
    export SYMPHONY_WORKFLOW_FILE="\$WORKFLOW"
    [ -n "\$PORT" ]      && export SYMPHONY_PORT="\$PORT"
    [ -n "\$LOGS_ROOT" ] && export SYMPHONY_LOGS_ROOT="\$LOGS_ROOT"
    exec "\$OTP_BIN" foreground
    ;;
  off)
    exec "\$OTP_BIN" stop
    ;;
  status)
    exec "\$OTP_BIN" pid
    ;;
  *)
    # Pass all other commands (dynamic-tools-mcp, etc.) straight through
    exec "\$OTP_BIN" "\$@"
    ;;
esac
WRAPPER

  chmod +x "$BIN_PATH"
  info "Installed symphony $VERSION -> $BIN_PATH"

  # Remind user to add INSTALL_DIR to PATH if needed
  case ":${PATH}:" in
    *":${INSTALL_DIR}:"*)
      ;;
    *)
      echo ""
      echo "  NOTE: ${INSTALL_DIR} is not in your PATH."
      echo "  Add the following line to your shell profile:"
      echo ""
      echo "    export PATH=\"${INSTALL_DIR}:\$PATH\""
      echo ""
      ;;
  esac

  echo ""
  echo "  Symphony $VERSION installed successfully."
  echo "  Run 'symphony --help' to get started."
  echo ""
}

main "$@"
